routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function () {

	Route::get('/', 'HomeController@index');
	Route::get('/home', 'HomeController@index');




		Route::resource('courses', 'CourseController');
		Route::resource('teachers', 'TeachersController');
		Route::resource('students', 'StudentController');
		Route::resource('modules', 'ModulesController');
		Route::resource('classes', 'ClassesController');

		


	
});

Auth::routes();

app/Teachers.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Teachers extends Model
{
    //
}

app/Http/Controllers/TeachersController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use App\Http\Requests\TeachersRequest;
use Illuminate\Support\Facades\Session;

class TeachersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(User $user)
    {
        $teachers = User::where('profile_id',1)->get();
        return view('teachers.index',compact('teachers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('teachers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TeachersRequest $request)
    {  
        User::create([
            'name' => $request->get('name'),
            'email' =>$request->get('email'),
            'password' => bcrypt($request->get('password')),
            'profile_id' => 1,
        ]);

        Session::flash('success', 'Professor adicionado com Sucesso!');

        return redirect()->action('TeachersController@index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Teachers  $teachers
     * @return \Illuminate\Http\Response
     */
    public function show(User $teachers,$id)
    {
        $teacher = $teachers->find($id);

        return view('teachers.show',compact('teacher'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Teachers  $teachers
     * @return \Illuminate\Http\Response
     */
    public function edit(User $teachers,$id)
    {
        $teacher = $teachers->find($id);

        return view('teachers.edit',compact('teacher'));
        
        return redirect()->action('TeachersController@index');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Teachers  $teachers
     * @return \Illuminate\Http\Response
     */
    public function update(TeachersRequest $request, User $teachers,$id)
    {
        $input = $request->except(['_method','_token']);

        $teachers->where('id',$id)->update($input);

        return redirect()->action('TeachersController@index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Teachers  $teachers
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $teachers,$id)
    {
        User::where('id',$id)->delete();

        return redirect()->action('TeachersController@index');
    }
}

resources/views/teachers/create.blade.php
@extends('layouts.app')

@section('content')

<div class="box">

    <div class="box-header">
        <h3 class="box-title">Cadastrar Professor</h3>
    </div>

    {!! Form::open(['url' => route('teachers.store'), 'method' => 'post', 'enctype' => 'multipart/form-data', 'accept-charset' => 'utf-8']) !!}

        <div class="box-body">

            @if(count($errors)>0)

            <div class="alert alert-danger" role="alert">  
                <ul>
                    @foreach($errors->all() as $message)
                        <li>{{$message}}</li>	
                    @endforeach
                <ul>	
            </div>
            
            @endif
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('Nome') !!}
                            {!! Form::text('name', null, ['required', 'class' => 'form-control', 'placeholder'=>'Nome do professor']) !!}
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('E-mail') !!}
                            {!! Form::text('email', null, ['required', 'class' => 'form-control', 'placeholder'=>'Digite o e-mail. Ex: exemplo@exemplo.com']) !!}
                        </div>
                    </div>
                </div>
               
               

                <div class="col-md-6">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('Senha') !!}
                            {!! Form::password('password', ['required', 'class' => 'form-control']) !!}
                        </div>
                    </div>
                </div>

            </div>

            <div class="form-group text-right">
                {!! Form::submit('Cadastrar', ['class' => 'btn btn-primary bgpersonalizado']) !!}
            </div>
        </div>

    {!! Form::close() !!}

</div>

@endsection

resources/views/teachers/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="box">

    <div class="box-header">
        <h3 class="box-title">Alterar dados do professor</h3>
    </div>

    {!! Form::open(['url' => route('teachers.update',$teacher->id) , 'method' => 'PUT', 'enctype' => 'multipart/form-data', 'accept-charset' => 'utf-8']) !!}

        <div class="box-body">
            @if(count($errors)>0)

            <div class="alert alert-danger" role="alert">  
                <ul>
                    @foreach($errors->all() as $message)
                        <li>{{$message}}</li>	
                    @endforeach
                <ul>	
            </div>
            
            @endif
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('Nome') !!}
                            {!! Form::text('name', $teacher->name , ['required', 'class' => 'form-control', 'placeholder'=>'Nome do professor']) !!}
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('E-mail') !!}
                            {!! Form::text('email', $teacher->email, ['required', 'class' => 'form-control', 'placeholder'=>'Digite o e-mail. Ex: exemplo@exemplo.com']) !!}
                        </div>
                    </div>
                </div>
              
              

              
            </div>

            <div class="form-group text-right">
                {!! Form::submit('Atualizar', ['class' => 'btn btn-primary bgpersonalizado']) !!}
            </div>
        </div>

    {!! Form::close() !!}

</div>

@endsection

resources/views/teachers/index.blade.php
@extends('layouts.app')

@section('content')

<div class="box">
    
    <div class="box-header">
        <h3 class="box-title">Professores</h3>
    </div>

    <div class="box-body table-responsive">

        <table id="datatable" class="display table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Email</th>
                   
                    <th>Ações</th>
                </tr>
            </thead>

            <tbody>
                
                @foreach($teachers as $teacher)

                <tr>

                    <td> {{$teacher->name}} </td>
                    
                    <td> {{$teacher->email}} </td>

                    <td>

                        <a href="{{ URL('/') }}/teachers/{{$teacher->id}}/edit" alt="Editar" title="Editar" class="btn btn-default">
                            <span class="glyphicon glyphicon-edit"></span>
                        </a>

                        <a href="{{ URL('/') }}/teachers/{{$teacher->id}}" alt="Visualizar" title="Visualizar" class="btn btn-default">
                            <span class="glyphicon glyphicon-share-alt"></span>
                        </a>

                        <form method="POST" action="{{ route('teachers.destroy', $teacher->id) }}" accept-charset="UTF-8">
                            {!! csrf_field() !!}
                            {!! method_field('DELETE') !!}
                            <button type="submit" onclick="return confirm('Tem certeza que quer deletar?')" class="btn btn-danger glyphicon glyphicon-trash">
                        </form>

                    </td>

                </tr>

                @endforeach

            </tbody> 

        </table>

        <br><br>

        <div class="form-group text-right">
            <a href="{{ URL('/') }}/teachers/create" class="btn btn-primary bgpersonalizado">Cadastrar</a>
        </div>
        
    </div>

</div>

@endsection

resources/views/teachers/show.blade.php
@extends('layouts.app')

@section('content')

<div class="box">

    <div class="box-header">
        <h3 class="box-title">Dados do professor</h3>
    </div>

   

        <div class="box-body">

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('Nome') !!}:
                            <span>{{ $teacher->name }}</span>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('E-mail') !!}:
                            <span>{{ $teacher->email }}</span>
                        </div>
                    </div>
                </div>
                
              
            </div>

            <div class="form-group text-right">
                <a href="{{ url('teachers/') }}" class="btn btn-primary bgpersonalizado">Voltar</a>
            </div>
        </div>



</div>

@endsection