routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function () {

	Route::get('/', 'HomeController@index');
	Route::get('/home', 'HomeController@index');




		Route::resource('courses', 'CourseController');
		Route::resource('teachers', 'TeachersController');
		Route::resource('students', 'StudentController');
		Route::resource('modules', 'ModulesController');
		Route::resource('classes', 'ClassesController');

		


	
});

Auth::routes();

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    //
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use App\Http\Requests\StudentRequest;
use Illuminate\Support\Facades\Session;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(User $student)
    {
        $students = User::where('profile_id',2)->get();
        return view('students.index',compact('students'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('students.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StudentRequest $request)
    {
        User::create([
            'name' => $request->get('name'),
            'email' =>$request->get('email'),
            'password' => bcrypt($request->get('password')),
            'profile_id' => 2,
        ]);

        Session::flash('success', 'Professor adicionado com Sucesso!');

        return redirect()->action('StudentController@index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function show(User $student)
    {
        return view('students.show',compact('student'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function edit(User $student)
    {
        return view('students.edit',compact('student'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function update(StudentRequest $request, User $student)
    {
        $input = $request->except(['_method','_token']);

        $student->update($input);

        return redirect()->action('StudentController@index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $student)
    {
        $student->delete();

        return redirect()->action('StudentController@index');
    }
}

resources/views/students/create.blade.php
@extends('layouts.app')

@section('content')

<div class="box">

    <div class="box-header">
        <h3 class="box-title">Cadastrar aluno</h3>
    </div>

    {!! Form::open(['url' =>  route('students.store') , 'method' => 'post', 'enctype' => 'multipart/form-data', 'accept-charset' => 'utf-8']) !!}

        <div class="box-body">
            @if(count($errors)>0)

            <div class="alert alert-danger" role="alert">  
                <ul>
                    @foreach($errors->all() as $message)
                        <li>{{$message}}</li>	
                    @endforeach
                <ul>	
            </div>
            
            @endif
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('Nome') !!}
                            {!! Form::text('name', null, ['required', 'class' => 'form-control', 'placeholder'=>'Nome do aluno']) !!}
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('E-mail') !!}
                            {!! Form::text('email', null, ['required', 'class' => 'form-control', 'placeholder'=>'Digite o e-mail. Ex: exemplo@exemplo.com']) !!}
                        </div>
                    </div>
                </div>
               

                <div class="col-md-6">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('Senha') !!}
                            {!! Form::password('password', ['required', 'class' => 'form-control']) !!}
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group text-right">
                {!! Form::submit('Cadastrar', ['class' => 'btn btn-primary bgpersonalizado']) !!}
            </div>
        </div>

    {!! Form::close() !!}

</div>

@endsection

resources/views/students/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="box">

    <div class="box-header">
        <h3 class="box-title">Alterar dados do aluno</h3>
    </div>

    {!! Form::open(['url' =>  route('students.update',$student->id), 'method' => 'PUT', 'enctype' => 'multipart/form-data', 'accept-charset' => 'utf-8']) !!}

        <div class="box-body">

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('Nome') !!}
                            {!! Form::text('name', $student->name, ['required', 'class' => 'form-control', 'placeholder'=>'Nome do aluno']) !!}
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('E-mail') !!}
                            {!! Form::text('email',  $student->email, ['required', 'class' => 'form-control', 'placeholder'=>'Digite o e-mail. Ex: exemplo@exemplo.com']) !!}
                        </div>
                    </div>
                </div>
               
            </div>

            <div class="form-group text-right">
                {!! Form::submit('Atualizar', ['class' => 'btn btn-primary bgpersonalizado']) !!}
            </div>
        </div>

    {!! Form::close() !!}

</div>

@endsection

resources/views/students/index.blade.php
@extends('layouts.app')

@section('content')

<div class="box">
    
    <div class="box-header">
        <h3 class="box-title">Alunos</h3>
    </div>

    <div class="box-body table-responsive">

        <table id="datatable" class="display table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Email</th>
                    <th>Ações</th>
                </tr>
            </thead>

            <tbody>
                
                @foreach($students as $student)

                <tr>

                    <td> {{$student->name}} </td>
                    
                    <td> {{$student->email}} </td>

                  

                    <td>

                        <a href="{{ URL('/') }}/students/{{$student->id}}/edit" alt="Editar" title="Editar" class="btn btn-default">
                            <span class="glyphicon glyphicon-edit"></span>
                        </a>

                        <a href="{{ URL('/') }}/students/{{$student->id}}" alt="Visualizar" title="Visualizar" class="btn btn-default">
                            <span class="glyphicon glyphicon-share-alt"></span>
                        </a>

                        <form method="POST" action="{{ route('students.destroy', $student->id) }}" accept-charset="UTF-8">
                            {!! csrf_field() !!}
                            {!! method_field('DELETE') !!}
                            <button type="submit" onclick="return confirm('Tem certeza que quer deletar?')" class="btn btn-danger glyphicon glyphicon-trash">
                        </form>

                    </td>

                </tr>

                @endforeach

            </tbody>  

        </table>

        <br><br>

        <div class="form-group text-right">
            <a href="{{ URL('/') }}/students/create" class="btn btn-primary bgpersonalizado">Cadastrar</a>
        </div>
        
    </div>

</div>

@endsection

resources/views/students/show.blade.php
@extends('layouts.app')

@section('content')

<div class="box">

    <div class="box-header">
        <h3 class="box-title">Dados do professor</h3>
    </div>

    {!! Form::open(['url' => 'reports', 'method' => 'post', 'enctype' => 'multipart/form-data', 'accept-charset' => 'utf-8']) !!}

        <div class="box-body">

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('Nome') !!}:
                            <span>{{ $student->name }}</span>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('E-mail') !!}:
                            <span>{{ $student->email }}</span>
                        </div>
                    </div>
                </div>
                
            </div>

            <div class="form-group text-right">
                <a href="{{ url('students/') }}" class="btn btn-primary bgpersonalizado">Voltar</a>
            </div>
        </div>

    {!! Form::close() !!}

</div>

@endsection