routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function () {

	Route::get('/', 'HomeController@index');
	Route::get('/home', 'HomeController@index');




		Route::resource('courses', 'CourseController');
		Route::resource('teachers', 'TeachersController');
		Route::resource('students', 'StudentController');
		Route::resource('modules', 'ModulesController');
		Route::resource('classes', 'ClassesController');

		


	
});

Auth::routes();

app/Modules.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
class Modules extends Model
{
      /**
     * The attributes that are mass assignable.
     *
     * @var array
     */

    protected  $table = 'modules';


    protected $fillable = [
        'name','course_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
         '_method','_token',
    ];

    public function course(){
        //relacionamento 1 para 1
        return $this->hasOne(Course::class,'id');
    }

    public function classes()
    {
        return $this->hasMany(Classes::class, 'modules_id', 'id');
    }

    public function modulesAll() {

        $result = DB::select('SELECT 
                m.name , m.id, c.name as name_course 
            FROM 
                modules m , course c 
            WHERE 
                m.course_id = c.id');

                return $result;
    }
}

app/Http/Controllers/ModulesController.php
<?php

namespace App\Http\Controllers;

use App\Modules;
use App\Course;
use Illuminate\Http\Request;
use App\Http\Requests\ModuleRequest;
use Illuminate\Support\Facades\Session;

class ModulesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Modules $modules)
    {
        $modules = $modules->modulesAll();
        return view('modules.index',compact('modules'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Course $courses)
    {
        $courses = $courses->where('status',1)->get();

        return view('modules.create',compact('courses'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ModuleRequest $request,Modules $modules)
    {

        if($input['course_id'] ==0){
            return \Redirect::back()->with('message',' Você precisa selecionar um curso.');
        }

        $modules->create($request->all());

        Session::flash('success', 'Curso adicionado com Sucesso!');

        return redirect()->action('ModulesController@index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Modules  $modules
     * @return \Illuminate\Http\Response
     */
    public function show($id,Modules $modules)
    {

        $modules = $modules->find($id);

        $courses = $modules->course()->first();

        $classes = $modules->classes()->get();
        
        return view('modules.show',compact('modules','courses','classes'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Modules  $modules
     * @return \Illuminate\Http\Response
     */
    public function edit(Modules $modules,Course $courses,$id)
    {
        $courses = $courses->where('status',1)->get();
        $modules = $modules->find($id);
        return view('modules.edit',compact('modules','courses'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Modules  $modules
     * @return \Illuminate\Http\Response
     */
    public function update(ModuleRequest $request,Modules $modules,$id)
    {
        $input = $request->except(['_method','_token']);

        if($input['course_id'] ==0){
            return \Redirect::back()->with('message',' Você precisa selecionar um curso.');
           
        }

        $modules->where('id',$id)->update($input);

        Session::flash('success', 'Módulo adicionado com Sucesso!');

        return redirect()->action('ModulesController@index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Modules  $modules
     * @return \Illuminate\Http\Response
     */
    public function destroy(Modules $modules)
    {
        $modules->delete();

        return redirect()->action('ModulesController@index');
    }
}

resources/views/modules/create.blade.php
@extends('layouts.app')

@section('content')

<div class="box">

    <div class="box-header">
        <h3 class="box-title">Cadastrar módulo</h3>
    </div>

    {!! Form::open(['url' =>  route('modules.store'), 'method' => 'post', 'enctype' => 'multipart/form-data', 'accept-charset' => 'utf-8']) !!}

        <div class="box-body">
            @if(count($errors)>0)

            <div class="alert alert-danger" role="alert">  
                <ul>
                    @foreach($errors->all() as $message)
                        <li>{{$message}}</li>	
                    @endforeach
                <ul>	
            </div>
            
            @endif
            @if (Session::has('message'))
            <div class="alert alert-danger">
               <?php echo Session::get('message')?>
            </div>
            @endif
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('Nome') !!}
                            {!! Form::text('name', null, ['required', 'class' => 'form-control', 'placeholder'=>'Nome do módulo']) !!}
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('Curso') !!}
                            <select required="" class="js-example-basic-single form-control" name="course_id">
                                <option selected="selected" value="0">Selecione uma opção</option>
                                @foreach($courses as $course)
                                    <option value="{{  $course->id }}">{{  $course->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                
                
            </div>

            <div class="form-group text-right">
                {!! Form::submit('Cadastrar', ['class' => 'btn btn-primary bgpersonalizado']) !!}
            </div>
        </div>

    {!! Form::close() !!}

</div>

@endsection

resources/views/modules/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="box">

    <div class="box-header">
        <h3 class="box-title">Alterar dados do módulo</h3>
    </div>

    {!! Form::open(['url' => route('modules.update',$modules->id), 'method' => 'PUT', 'enctype' => 'multipart/form-data', 'accept-charset' => 'utf-8']) !!}

        <div class="box-body">
            @if(count($errors)>0)

            <div class="alert alert-danger" role="alert">  
                <ul>
                    @foreach($errors->all() as $message)
                        <li>{{$message}}</li>	
                    @endforeach
                <ul>	
            </div>
     
            @endif

            @if (Session::has('message'))
            <div class="alert alert-danger">
               <?php echo Session::get('message')?>
            </div>
            @endif
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('Nome') !!}
                            {!! Form::text('name', $modules->name, ['required', 'class' => 'form-control', 'placeholder'=>'Nome do módulo']) !!}
                        </div>
                    </div>
                </div>
                
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('Curso') !!}
                            <select required="required" class="js-example-basic-single form-control" name="course_id">
                                <option selected="selected" valye="0">Selecione uma opção</option>
                                @foreach($courses as $course)
                                    <option {{ $course->id ==  $modules->course_id ? 'selected' : '' }} value="{{  $course->id }}">{{  $course->name }}</option>
                                @endforeach
                            </select>
                         
                        </div>
                    </div>

           

            <div class="form-group text-right">
                {!! Form::submit('Atualizar', ['class' => 'btn btn-primary bgpersonalizado']) !!}
            </div>
        </div>

    {!! Form::close() !!}

</div>

@endsection

resources/views/modules/index.blade.php
@extends('layouts.app')

@section('content')

<div class="box">
    
    <div class="box-header">
        <h3 class="box-title">Módulos</h3>
    </div>

    <div class="box-body table-responsive">

        <table id="datatable" class="display table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Curso</th>
                    <th>Ações</th>
                </tr>
            </thead>

            <tbody>
                
                @foreach($modules as $module)

                <tr>

                    <td> {{$module->name}} </td>

                    <td>  {{$module->name_course}}  </td>
                    
                    <td>

                        <a href="{{ URL('/') }}/modules/{{$module->id}}/edit" alt="Editar" title="Editar" class="btn btn-default">
                            <span class="glyphicon glyphicon-edit"></span>
                        </a>

                        <a href="{{ URL('/') }}/modules/{{$module->id}}" alt="Visualizar" title="Visualizar" class="btn btn-default">
                            <span class="glyphicon glyphicon-share-alt"></span>
                        </a>

                        <form method="POST" action="{{ route('modules.destroy', $module->id) }}" accept-charset="UTF-8">
                            {!! csrf_field() !!}
                            {!! method_field('DELETE') !!}
                            <button type="submit" onclick="return confirm('Tem certeza que quer deletar?')" class="btn btn-danger glyphicon glyphicon-trash">
                        </form>

                    </td>

                </tr>

                @endforeach

            </tbody> 

        </table>

        <br><br>

        <div class="form-group text-right">
            <a href="{{ URL('/') }}/modules/create" class="btn btn-primary bgpersonalizado">Cadastrar</a>
        </div>
        
    </div>

</div>

@endsection

resources/views/modules/show.blade.php
@extends('layouts.app')

@section('content')

<div class="box">

    <div class="box-header">
        <h3 class="box-title">Dados do módulo</h3>
    </div>

    

        <div class="box-body">

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('Nome') !!}:
                            <span>{{ $modules->name }}</span>
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('Curso') !!}:
                            <span>{{ $courses->name }}</span>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('Cronograma') !!}:
                            <ul>
                                @for($i=0; $i < count($classes) ;$i++ )
                                    <li>{{  $classes[$i]->name }}</li>
                                @endfor
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

        </div>


</div>

@endsection