routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function () {

	Route::get('/', 'HomeController@index');
	Route::get('/home', 'HomeController@index');




		Route::resource('courses', 'CourseController');
		Route::resource('teachers', 'TeachersController');
		Route::resource('students', 'StudentController');
		Route::resource('modules', 'ModulesController');
		Route::resource('classes', 'ClassesController');

		


	
});

Auth::routes();

app/Http/Controllers/ClassesController.php
<?php

namespace App\Http\Controllers;

use App\Classes;
use Illuminate\Http\Request;
use App\Modules;
use App\Http\Requests\ClassesRequest;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\DB;
class ClassesController extends Controller

{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Classes $classes,Modules $modules)
    {
       $classes = $classes->classesAll();

        return view('classes.index',compact('classes','modules'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Modules $modules)
    {
        $modules = $modules->get();

        return view('classes.create',compact('modules'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ClassesRequest $request,Classes $classes)
    {
        
        if($request->get('modules_id')==0){
            return \Redirect::back()->with('message',' Você precisa selecionar um módulo.');
        }

        $classes->create($request->all());

        Session::flash('success', 'Aula criada com sucesso !');

        return redirect()->action('ClassesController@index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Classes  $classes
     * @return \Illuminate\Http\Response
     */
    public function show($id,Classes $classes)
    {

        $classes = $classes->find($id);

        $modules = $classes->modules()->first();

        return view('classes.show',compact('classes','modules'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Classes  $classes
     * @return \Illuminate\Http\Response
     */
    public function edit($id,Classes $classes,Modules $modules )
    {
    
        $classes = $classes->find($id);

        $modules = $modules->get();

        return view('classes.edit',compact('classes','modules'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Classes  $classes
     * @return \Illuminate\Http\Response
     */
    public function update($id,ClassesRequest $request,Classes $classes)
    {

        $input = $request->except(['_method','_token']);

        if($input['modules_id']==0){
            return \Redirect::back()->with('message',' Você precisa selecionar um módulo.');
        }

        $classes->where('id',$id)->update( $input);

        Session::flash('success', 'Atualizado com sucesso !');

        return redirect()->action('ClassesController@index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Classes  $classes
     * @return \Illuminate\Http\Response
     */
    public function destroy($id, Classes $classes)
    {
        $classes->where('id',$id)->delete();

        return redirect()->action('ClassesController@index');
    }
}

resources/views/classes/create.blade.php
@extends('layouts.app')

@section('content')

<div class="box">

    <div class="box-header">
        <h3 class="box-title">Cadastrar aula</h3>
    </div>

    {!! Form::open(['url' =>  route('classes.store'), 'method' => 'post', 'enctype' => 'multipart/form-data', 'accept-charset' => 'utf-8']) !!}

        <div class="box-body">
            @if(count($errors)>0)

            <div class="alert alert-danger" role="alert">  
                <ul>
                    @foreach($errors->all() as $message)
                        <li>{{$message}}</li>	
                    @endforeach
                <ul>	
            </div>
            
            @endif
            @if (Session::has('message'))
            <div class="alert alert-danger">
               <?php echo Session::get('message')?>
            </div>
            @endif
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('Nome categoria') !!}
                            {!! Form::text('name', null, ['required', 'class' => 'form-control', 'placeholder'=>'Nome da categoria']) !!}
                        </div>
                    </div>
                </div>
                
                <div class="col-md-3">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('Módulo') !!}
                            <select required="" class="js-example-basic-single form-control" name="modules_id">
                                <option selected="selected" value="0">Selecione uma opção</option>
                                @foreach($modules as $module)
                                    <option value="{{  $module->id }}">{{  $module->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('Duração') !!}
                            {!! Form::time('duration', null, ['required', 'class' => 'form-control','placeholder'=>'Duração da aula']) !!}
                        </div>
                    </div>
                </div>
                
            </div>

            <div class="form-group text-right">
                {!! Form::submit('Cadastrar', ['class' => 'btn btn-primary bgpersonalizado']) !!}
            </div>
        </div>

    {!! Form::close() !!}

</div>

@endsection

resources/views/classes/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="box">

    <div class="box-header">
        <h3 class="box-title">Alterar dados da aula</h3>
    </div>

    {!! Form::open(['url' => route('classes.update',$classes->id), 'method' => 'PUT', 'enctype' => 'multipart/form-data', 'accept-charset' => 'utf-8']) !!}

        <div class="box-body">
            @if(count($errors)>0)

            <div class="alert alert-danger" role="alert">  
                <ul>
                    @foreach($errors->all() as $message)
                        <li>{{$message}}</li>	
                    @endforeach
                <ul>	
            </div>
            
            @endif
            @if (Session::has('message'))
            <div class="alert alert-danger">
               <?php echo Session::get('message')?>
            </div>
            @endif
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('Nome categoria') !!}
                            {!! Form::text('name', $classes->name, ['required', 'class' => 'form-control', 'placeholder'=>'Nome da categoria']) !!}
                        </div>
                    </div>
                </div>
                
                <div class="col-md-3">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('Módulo') !!}
                            <select required="" class="js-example-basic-single form-control" name="modules_id">
                                <option selected="selected" value="0">Selecione uma opção</option>
                                @foreach($modules as $module)
                                    <option  {{ $module->id ==  $classes->modules_id ? 'selected' : '' }}  value="{{  $module->id }}">{{  $module->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('Duração') !!}
                            {!! Form::time('duration', $classes->duration, ['required', 'class' => 'form-control','placeholder'=>'Duração da aula']) !!}
                        </div>
                    </div>
                </div>
                
            </div>

            <div class="form-group text-right">
                {!! Form::submit('Atualizar', ['class' => 'btn btn-primary bgpersonalizado']) !!}
            </div>
        </div>

    {!! Form::close() !!}

</div>

@endsection

resources/views/classes/index.blade.php
@extends('layouts.app')

@section('content')

<div class="box">
    
    <div class="box-header">
        <h3 class="box-title">Aulas</h3>
    </div>

    <div class="box-body table-responsive">

        <table id="datatable" class="display table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Nome da Aula</th>
                    <th>Módulo</th>
                    <th>Duração</th>
                    <th>Ações</th>
                </tr>
            </thead>
 
            <tbody>
                
                @foreach($classes as $class)

                <tr>

                    <td> {{$class->name}} </td>
                    
                    <td> {{$class->name_module}}  </td>

                    <td> 
                        {{$class->duration}}
                    </td>

                    <td>

                        <a href="{{ URL('/') }}/classes/{{$class->id}}/edit" alt="Editar" title="Editar" class="btn btn-default">
                            <span class="glyphicon glyphicon-edit"></span>
                        </a>

                        <a href="{{ URL('/') }}/classes/{{$class->id}}" alt="Visualizar" title="Visualizar" class="btn btn-default">
                            <span class="glyphicon glyphicon-share-alt"></span>
                        </a>

                        <form method="POST" action="{{ route('classes.destroy', $class->id) }}" accept-charset="UTF-8">
                            {!! csrf_field() !!}
                            {!! method_field('DELETE') !!}
                            <button type="submit" onclick="return confirm('Tem certeza que quer deletar?')" class="btn btn-danger glyphicon glyphicon-trash">
                        </form>

                    </td>

                </tr>

                @endforeach

            </tbody>  

        </table>

        <br><br>

        <div class="form-group text-right">
            <a href="{{ URL('/') }}/classes/create" class="btn btn-primary bgpersonalizado">Cadastrar</a>
        </div>
        
    </div>

</div>

@endsection

resources/views/classes/show.blade.php
@extends('layouts.app')

@section('content')

<div class="box">

    <div class="box-header">
        <h3 class="box-title">Dados da aula</h3>
    </div>

        <div class="box-body">

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('Nome') !!}:
                            <span>{{ $classes->name }}</span>
                        </div>
                    </div>
                </div>
                
                <div class="col-md-3">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('Módulo') !!}:
                            <span>{{ $modules->name }}</span>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <div class="input text">
                            {!! Form::label('Duração') !!}: 
                            <span>{{ $classes->duration }}</span>
                        </div>
                    </div>
                </div>
                
            </div>

        </div>



</div>

@endsection